os: linux
language: php
php:
  - 7.4
# master only
branches:
  only:
    - master
# Download Cecil and theme(s)
install:
  - curl -sSOL https://cecil.app/cecil.phar && php cecil.phar --version
  - composer install --prefer-dist --no-dev --no-progress --no-interaction
# Run Cecil build
script:
  - php cecil.phar build -v
# Deploy to GitHub Pages
deploy:
  provider: pages
  edge: true
  token: $GH_TOKEN # set this env. variable in Travis CI settings
  local_dir: _site
  on:
    branch: master
