name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, gd, imagick, intl, gettext

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install theme(s)
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --prefer-dist --no-dev --no-progress --no-interaction

    - name: Build site with Cecil
      env:
        CECIL_BASEURL: ${{ secrets.CECIL_BASEURL }}
      run: |
        echo "### Downloading Cecil $CECIL_VERSION"
        if [[ -z "$CECIL_VERSION" ]]; then
          curl -sSOL https://cecil.app/cecil.phar
        else
          curl -sSOL https://cecil.app/download/$CECIL_VERSION/cecil.phar
        fi
        php cecil.phar --version
        echo "### Building Cecil static site"
        php cecil.phar build -v
        echo "### Cecil Action done"

    - name: Upload site to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: _site
        path: _site/
        if-no-files-found: error

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download site from Artifacts
      uses: actions/download-artifact@v2
      with:
        name: _site
        path: _site/

    - name: Deploy site to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: arnaud@ligny.org
        build_dir: _site
